#!/bin/sh
case "$QUTE_URL" in
    https://teams.microsoft.com/*|https://teams.live.com/*|msteams:*)
        nohup xdg-open "$QUTE_URL" >/dev/null 2>&1 &
        ;;
    *)
        printf 'Not a Teams URL\n' >&2
        exit 1
        ;;
esac

