# Auto-generated by the rice — don't hand-edit.
from pathlib import Path

c.colors.webpage.bg = "#0E0C10"

c.colors.statusbar.normal.bg = "#0E0C10"
c.colors.statusbar.normal.fg = "#e9e0e6"
c.colors.statusbar.insert.bg = "#9F738D"
c.colors.statusbar.insert.fg = "#0E0C10"
c.colors.statusbar.command.bg = "#0E0C10"
c.colors.statusbar.command.fg = "#e9e0e6"
c.colors.statusbar.url.fg = "#e9e0e6"
c.colors.statusbar.url.success.http.fg = "#B8A4BA"
c.colors.statusbar.url.success.https.fg = "#B8A4BA"
c.colors.statusbar.url.error.fg = "#A14F5E"
c.colors.statusbar.url.warn.fg = "#A14F5E"
c.colors.statusbar.progress.bg = "#9F738D"

c.colors.tabs.bar.bg = "#0E0C10"
c.colors.tabs.odd.bg = "#0E0C10"
c.colors.tabs.odd.fg = "#e9e0e6"
c.colors.tabs.even.bg = "#0E0C10"
c.colors.tabs.even.fg = "#e9e0e6"
c.colors.tabs.selected.odd.bg = "#9F738D"
c.colors.tabs.selected.odd.fg = "#0E0C10"
c.colors.tabs.selected.even.bg = "#9F738D"
c.colors.tabs.selected.even.fg = "#0E0C10"
c.colors.tabs.indicator.start = "#B8A4BA"
c.colors.tabs.indicator.stop = "#9F738D"
c.colors.tabs.indicator.error = "#A14F5E"
c.tabs.padding = {'top': 6, 'bottom': 6, 'left': 10, 'right': 10}

c.colors.completion.fg = "#e9e0e6"
c.colors.completion.odd.bg = "#0E0C10"
c.colors.completion.even.bg = "#0E0C10"
c.colors.completion.category.bg = "#0E0C10"
c.colors.completion.category.fg = "#9F738D"
c.colors.completion.category.border.top = "#a39ca1"
c.colors.completion.category.border.bottom = "#a39ca1"
c.colors.completion.item.selected.bg = "#9F738D"
c.colors.completion.item.selected.fg = "#0E0C10"
c.colors.completion.item.selected.border.top = "#9F738D"
c.colors.completion.item.selected.border.bottom = "#9F738D"
c.colors.completion.item.selected.match.fg = "#0E0C10"
c.colors.completion.match.fg = "#B8A4BA"
c.colors.completion.scrollbar.fg = "#9F738D"
c.colors.completion.scrollbar.bg = "#0E0C10"

c.colors.hints.bg = "#9F738D"
c.colors.hints.fg = "#0E0C10"
c.colors.hints.match.fg = "#B8A4BA"
c.hints.radius = 8

c.colors.downloads.bar.bg = "#0E0C10"
c.colors.downloads.start.bg = "#9F738D"
c.colors.downloads.start.fg = "#0E0C10"
c.colors.downloads.stop.bg = "#B8A4BA"
c.colors.downloads.stop.fg = "#0E0C10"
c.colors.downloads.error.bg = "#A14F5E"
c.colors.downloads.error.fg = "#0E0C10"

c.colors.messages.info.bg = "#0E0C10"
c.colors.messages.info.fg = "#e9e0e6"
c.colors.messages.info.border = "#a39ca1"
c.colors.messages.warning.bg = "#0E0C10"
c.colors.messages.warning.fg = "#A14F5E"
c.colors.messages.warning.border = "#A14F5E"
c.colors.messages.error.bg = "#A14F5E"
c.colors.messages.error.fg = "#0E0C10"
c.colors.messages.error.border = "#A14F5E"

c.colors.prompts.bg = "#0E0C10"
c.colors.prompts.fg = "#e9e0e6"
c.colors.prompts.border = "1px solid #a39ca1"
c.colors.prompts.selected.bg = "#9F738D"
c.colors.prompts.selected.fg = "#0E0C10"

c.colors.contextmenu.menu.bg = "#0E0C10"
c.colors.contextmenu.menu.fg = "#e9e0e6"
c.colors.contextmenu.selected.bg = "#9F738D"
c.colors.contextmenu.selected.fg = "#0E0C10"

# Start page wiring
_startpage = Path(__file__).parent / "startpage.html"
if _startpage.exists():
    _sp_url = f"file://{_startpage}"
    c.url.start_pages = [_sp_url]
    c.url.default_page = _sp_url
