# Auto-generated by the rice — don't hand-edit.
from pathlib import Path

c.colors.webpage.bg = "#090c0a"

c.colors.statusbar.normal.bg = "#090c0a"
c.colors.statusbar.normal.fg = "#a1bcae"
c.colors.statusbar.insert.bg = "#3D634F"
c.colors.statusbar.insert.fg = "#090c0a"
c.colors.statusbar.command.bg = "#090c0a"
c.colors.statusbar.command.fg = "#a1bcae"
c.colors.statusbar.url.fg = "#a1bcae"
c.colors.statusbar.url.success.http.fg = "#4C7B63"
c.colors.statusbar.url.success.https.fg = "#4C7B63"
c.colors.statusbar.url.error.fg = "#1E4331"
c.colors.statusbar.url.warn.fg = "#1E4331"
c.colors.statusbar.progress.bg = "#3D634F"

c.colors.tabs.bar.bg = "#090c0a"
c.colors.tabs.odd.bg = "#090c0a"
c.colors.tabs.odd.fg = "#a1bcae"
c.colors.tabs.even.bg = "#090c0a"
c.colors.tabs.even.fg = "#a1bcae"
c.colors.tabs.selected.odd.bg = "#3D634F"
c.colors.tabs.selected.odd.fg = "#090c0a"
c.colors.tabs.selected.even.bg = "#3D634F"
c.colors.tabs.selected.even.fg = "#090c0a"
c.colors.tabs.indicator.start = "#4C7B63"
c.colors.tabs.indicator.stop = "#3D634F"
c.colors.tabs.indicator.error = "#1E4331"
c.tabs.padding = {'top': 6, 'bottom': 6, 'left': 10, 'right': 10}

c.colors.completion.fg = "#a1bcae"
c.colors.completion.odd.bg = "#090c0a"
c.colors.completion.even.bg = "#090c0a"
c.colors.completion.category.bg = "#090c0a"
c.colors.completion.category.fg = "#3D634F"
c.colors.completion.category.border.top = "#708379"
c.colors.completion.category.border.bottom = "#708379"
c.colors.completion.item.selected.bg = "#3D634F"
c.colors.completion.item.selected.fg = "#090c0a"
c.colors.completion.item.selected.border.top = "#3D634F"
c.colors.completion.item.selected.border.bottom = "#3D634F"
c.colors.completion.item.selected.match.fg = "#090c0a"
c.colors.completion.match.fg = "#4C7B63"
c.colors.completion.scrollbar.fg = "#3D634F"
c.colors.completion.scrollbar.bg = "#090c0a"

c.colors.hints.bg = "#3D634F"
c.colors.hints.fg = "#090c0a"
c.colors.hints.match.fg = "#4C7B63"
c.hints.radius = 8

c.colors.downloads.bar.bg = "#090c0a"
c.colors.downloads.start.bg = "#3D634F"
c.colors.downloads.start.fg = "#090c0a"
c.colors.downloads.stop.bg = "#4C7B63"
c.colors.downloads.stop.fg = "#090c0a"
c.colors.downloads.error.bg = "#1E4331"
c.colors.downloads.error.fg = "#090c0a"

c.colors.messages.info.bg = "#090c0a"
c.colors.messages.info.fg = "#a1bcae"
c.colors.messages.info.border = "#708379"
c.colors.messages.warning.bg = "#090c0a"
c.colors.messages.warning.fg = "#1E4331"
c.colors.messages.warning.border = "#1E4331"
c.colors.messages.error.bg = "#1E4331"
c.colors.messages.error.fg = "#090c0a"
c.colors.messages.error.border = "#1E4331"

c.colors.prompts.bg = "#090c0a"
c.colors.prompts.fg = "#a1bcae"
c.colors.prompts.border = "1px solid #708379"
c.colors.prompts.selected.bg = "#3D634F"
c.colors.prompts.selected.fg = "#090c0a"

c.colors.contextmenu.menu.bg = "#090c0a"
c.colors.contextmenu.menu.fg = "#a1bcae"
c.colors.contextmenu.selected.bg = "#3D634F"
c.colors.contextmenu.selected.fg = "#090c0a"

# Start page wiring
_startpage = Path(__file__).parent / "startpage.html"
if _startpage.exists():
    _sp_url = f"file://{_startpage}"
    c.url.start_pages = [_sp_url]
    c.url.default_page = _sp_url
