# Auto-generated by the rice — don't hand-edit.
from pathlib import Path

c.colors.webpage.bg = "#0b0a17"

c.colors.statusbar.normal.bg = "#0b0a17"
c.colors.statusbar.normal.fg = "#dbcace"
c.colors.statusbar.insert.bg = "#A58AA0"
c.colors.statusbar.insert.fg = "#0b0a17"
c.colors.statusbar.command.bg = "#0b0a17"
c.colors.statusbar.command.fg = "#dbcace"
c.colors.statusbar.url.fg = "#dbcace"
c.colors.statusbar.url.success.http.fg = "#E3AA9D"
c.colors.statusbar.url.success.https.fg = "#E3AA9D"
c.colors.statusbar.url.error.fg = "#98849E"
c.colors.statusbar.url.warn.fg = "#98849E"
c.colors.statusbar.progress.bg = "#A58AA0"

c.colors.tabs.bar.bg = "#0b0a17"
c.colors.tabs.odd.bg = "#0b0a17"
c.colors.tabs.odd.fg = "#dbcace"
c.colors.tabs.even.bg = "#0b0a17"
c.colors.tabs.even.fg = "#dbcace"
c.colors.tabs.selected.odd.bg = "#A58AA0"
c.colors.tabs.selected.odd.fg = "#0b0a17"
c.colors.tabs.selected.even.bg = "#A58AA0"
c.colors.tabs.selected.even.fg = "#0b0a17"
c.colors.tabs.indicator.start = "#E3AA9D"
c.colors.tabs.indicator.stop = "#A58AA0"
c.colors.tabs.indicator.error = "#98849E"
c.tabs.padding = {'top': 6, 'bottom': 6, 'left': 10, 'right': 10}

c.colors.completion.fg = "#dbcace"
c.colors.completion.odd.bg = "#0b0a17"
c.colors.completion.even.bg = "#0b0a17"
c.colors.completion.category.bg = "#0b0a17"
c.colors.completion.category.fg = "#A58AA0"
c.colors.completion.category.border.top = "#998d90"
c.colors.completion.category.border.bottom = "#998d90"
c.colors.completion.item.selected.bg = "#A58AA0"
c.colors.completion.item.selected.fg = "#0b0a17"
c.colors.completion.item.selected.border.top = "#A58AA0"
c.colors.completion.item.selected.border.bottom = "#A58AA0"
c.colors.completion.item.selected.match.fg = "#0b0a17"
c.colors.completion.match.fg = "#E3AA9D"
c.colors.completion.scrollbar.fg = "#A58AA0"
c.colors.completion.scrollbar.bg = "#0b0a17"

c.colors.hints.bg = "#A58AA0"
c.colors.hints.fg = "#0b0a17"
c.colors.hints.match.fg = "#E3AA9D"
c.hints.radius = 8

c.colors.downloads.bar.bg = "#0b0a17"
c.colors.downloads.start.bg = "#A58AA0"
c.colors.downloads.start.fg = "#0b0a17"
c.colors.downloads.stop.bg = "#E3AA9D"
c.colors.downloads.stop.fg = "#0b0a17"
c.colors.downloads.error.bg = "#98849E"
c.colors.downloads.error.fg = "#0b0a17"

c.colors.messages.info.bg = "#0b0a17"
c.colors.messages.info.fg = "#dbcace"
c.colors.messages.info.border = "#998d90"
c.colors.messages.warning.bg = "#0b0a17"
c.colors.messages.warning.fg = "#98849E"
c.colors.messages.warning.border = "#98849E"
c.colors.messages.error.bg = "#98849E"
c.colors.messages.error.fg = "#0b0a17"
c.colors.messages.error.border = "#98849E"

c.colors.prompts.bg = "#0b0a17"
c.colors.prompts.fg = "#dbcace"
c.colors.prompts.border = "1px solid #998d90"
c.colors.prompts.selected.bg = "#A58AA0"
c.colors.prompts.selected.fg = "#0b0a17"

c.colors.contextmenu.menu.bg = "#0b0a17"
c.colors.contextmenu.menu.fg = "#dbcace"
c.colors.contextmenu.selected.bg = "#A58AA0"
c.colors.contextmenu.selected.fg = "#0b0a17"

# Start page wiring
_startpage = Path(__file__).parent / "startpage.html"
if _startpage.exists():
    _sp_url = f"file://{_startpage}"
    c.url.start_pages = [_sp_url]
    c.url.default_page = _sp_url
