# Font
font_family      JetBrains Mono Nerd Font
font_size 11.0

# Cursor

# Enables the cursor trail animation
cursor_trail 10

# Makes the trail last longer before fading away
cursor_trail_decay 0.2 0.75

# Starts the trail even with very small movements
cursor_trail_start_threshold 1

cursor_shape beam
cursor_shape_unfocused hollow

# Sets the minimum distance the cursor must move to trigger the animation
cursor_trail_start_threshold 2


# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell fish

# for tmux setup
#shell tmux new-session -A -s main
# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0

# split behavior:

map ctrl+shift+enter launch --cwd=current
map ctrl+shift+l launch --cwd=current --location=hsplit
map ctrl+shift+w close_window

#map ctrl+alt+t launch --type=tab --cwd=current zsh -c "tmux attach || tmux"


# kitty.conf
#background_image /home/kamal/Pictures/wall/bg_kitty.jpeg
#background_image_layout scaled
# try: scaled | tiled | clamped
background_tint 0.75
enable_audio_bell no
input_delay 1

background_opacity 0.5
background_blur 80
dynamic_background_opacity no
include colors-wal.conf
