# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#131315

# Main text color
theme[main_fg]=#e4e2e3

# Title color for boxes
theme[title]=#e4e2e3

# Highlight color for keyboard shortcuts
theme[hi_fg]=#b5c9de

# Background color of selected item in processes box
theme[selected_bg]=#1f2021

# Foreground color of selected item in processes box
theme[selected_fg]=#b5c9de

# Color of inactive/disabled text
theme[inactive_fg]=#8d9196

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#d8bfda

# Background color of the percentage meters
theme[meter_bg]=#8d9196

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#d8bfda

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#9bc2ff
theme[mem_box]=#b5e7ff
theme[net_box]=#aebdf1
theme[proc_box]=#85c2ff

# Box divider line and small boxes line color
theme[div_line]=#43474c

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#b5e7ff
theme[temp_mid]=#d0f9f4
theme[temp_end]=#97b2ff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#bee5ff
theme[cpu_mid]=#91cdff
theme[cpu_end]=#aacfff

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#9bc2ff
theme[free_mid]=#aacfff
theme[free_end]=#85c2ff

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#91cdff
theme[cached_mid]=#85c2ff
theme[cached_end]=#aacfff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#e0c2f9
theme[available_mid]=#aebdf1
theme[available_end]=#97b2ff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#b5e7ff
theme[used_mid]=#bee5ff
theme[used_end]=#b9e0ff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#e0c2f9
theme[download_mid]=#aebdf1
theme[download_end]=#97b2ff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#b5e7ff
theme[upload_mid]=#bee5ff
theme[upload_end]=#b9e0ff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#91cdff
theme[process_mid]=#aacfff
theme[process_end]=#9bc2ff
