#!/usr/bin/env fish

set -l script_dir (cd -- (dirname (status --current-filename)); and pwd)
source "$script_dir/paths.fish"

set -l colors $QS_WAL_COLORS
if test (count $argv) -ge 1; and test -n "$argv[1]"
    set colors $argv[1]
end

if not test -s "$colors"
    echo "write-hypr-theme: missing colors.json at $colors" >&2
    exit 1
end

set -l extracted (python3 -c '
import json, sys
c = json.load(open(sys.argv[1]))["colors"]
print(c["color4"].lstrip("#"))
print(c["color0"].lstrip("#"))
' "$colors")
or exit $status
set -l active $extracted[1]
set -l inactive $extracted[2]

set -l out "$HOME/.config/hypr/colors-wal.lua"
mkdir -p (dirname "$out"); or exit $status

printf '%s\n' "-- generated by write-hypr-theme.fish, don't hand-edit this one
package.loaded[\"colors-wal\"] = nil
package.preload[\"colors-wal.lua\"] = function() return require(\"colors-wal\") end

hl.config({
    general = {
        border_size = 1,
        col = {
            active_border = \"rgba($active""ff)\",
            inactive_border = \"rgba($inactive""aa)\",
        },
    },
    decoration = { rounding = 12 },
    animations = { enabled = false },
})

pcall(function()
  hl.config({ decoration = { blur = { enabled = true, size = 8, passes = 4, vibrancy = 0.3 } } })
  -- Keep blur scoped to Yahpax surfaces that intentionally use translucency.
  hl.layer_rule({ match = { namespace = \"quickshell-bar\" }, blur = true, ignore_alpha = 0.08 })
end)
" > "$out"

hyprctl reload >/dev/null 2>&1; or true
echo "Hyprland colors updated"
