-- generated by write-hypr-theme.fish, don't hand-edit this one
package.loaded["colors-wal"] = nil
package.preload["colors-wal.lua"] = function() return require("colors-wal") end

hl.config({
    general = {
        border_size = 1,
        col = {
            active_border = {
                colors = { "rgba(7EC1AEff)", "rgba(C8AC8Aff)" },
                angle = 45,
            },
            inactive_border = "rgba(253633aa)",
        },
    },
    decoration = { rounding = 12 },
    animations = { enabled = true },
})

pcall(function()
  hl.config({ decoration = { blur = { enabled = true, size = 8, passes = 4, vibrancy = 0.3 } } })
  for _, ns in ipairs({ "quickshell", "quickshell-notifications",
                        "quickshell-holorings", "quickshell-sysinfo",
                        "quickshell-bigclock" }) do
      hl.layer_rule({ match = { namespace = ns }, blur = true, ignore_alpha = 0.2 })
  end
  -- the bar pill is way more transparent (0.14) than everything else
  -- (0.5), so it needs its own ignore_alpha below that or blur skips
  -- the pixels entirely
  hl.layer_rule({ match = { namespace = "quickshell-bar" }, blur = true, ignore_alpha = 0.08 })
end)
pcall(function()
    hl.curve("riceGlide", { type = "bezier", points = { {0.22, 1.0}, {0.36, 1.0} } })
    hl.curve("riceSoft",  { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })
    hl.animation({ leaf = "global",     enabled = true, speed = 4,   bezier = "riceGlide" })
    hl.animation({ leaf = "windows",    enabled = true, speed = 4,   bezier = "riceGlide", style = "popin 85%" })
    hl.animation({ leaf = "windowsOut", enabled = true, speed = 4.5, bezier = "riceSoft",  style = "popin 85%" })
    hl.animation({ leaf = "fade",       enabled = true, speed = 4,   bezier = "riceSoft" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 5,   bezier = "riceGlide", style = "slidefade 12%" })
    hl.animation({ leaf = "layersIn",   enabled = true, speed = 4,   bezier = "riceGlide", style = "slide" })
    hl.animation({ leaf = "layersOut",  enabled = true, speed = 4,   bezier = "riceSoft" })
end)

