listener {
    timeout = 100

    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

    condition_cmd = ! playerctl --all-players status 2>/dev/null | grep -q '^Playing$'
    condition_retry = 30
}

listener {
    timeout = 3600

    on-timeout = systemctl poweroff

    condition_cmd = ! playerctl --all-players status 2>/dev/null | grep -q '^Playing$'
    condition_retry = 30
}
