-- generated by write-hypr-theme.fish, don't hand-edit this one
package.loaded["colors-wal"] = nil
package.preload["colors-wal.lua"] = function() return require("colors-wal") end

hl.config({
    general = {
        col = {
            active_border = "rgba(6D99E1ff)",
            inactive_border = "rgba(353071aa)",
        },
    },
})

