[general]

framerate = 60

bars = 64

autosens = 1

lower_cutoff_freq = 25

higher_cutoff_freq = 18000

sleep_timer = 0


[input]

method = pipewire

source = auto

sample_rate = 48000

sample_bits = 16

channels = mono

mono_option = average


[output]

method = raw

raw_target = /dev/stdout

data_format = ascii

ascii_max_range = 1000

bar_delimiter = 32

frame_delimiter = 10


[smoothing]

noise_reduction = 8

monstercat = 0

waves = 0
