#!/usr/bin/env python3
"""
apply-qutebrowser-colors.py [colors.json] [output_dir]

Generates <output_dir>/colors-wal.py with pywal palette and startpage settings,
wires it into config.py if present, and reloads any running qutebrowser instance.
"""

import subprocess
import sys
from pathlib import Path
from color_utils import load_colors
from paths import QUTEBROWSER_CONFIG, WAL_COLORS


def main():
    colors_json_path = (
        Path(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1]
        else WAL_COLORS
    )
    output_dir = (
        Path(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2]
        else QUTEBROWSER_CONFIG
    )

    if not colors_json_path.exists():
        print(f"Error: {colors_json_path} not found", file=sys.stderr)
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    data = load_colors(colors_json_path)

    bg = data["special"]["background"]
    fg = data["special"]["foreground"]
    colors = data["colors"]
    accent = colors["color4"]
    accent2 = colors["color6"]
    error = colors["color1"]
    muted = colors["color8"]

    hints_radius = 8
    tabs_padding = "{'top': 6, 'bottom': 6, 'left': 10, 'right': 10}"
    selected_bg, selected_fg = accent, bg

    output = f"""# Auto-generated by the rice — don't hand-edit.
from pathlib import Path

c.colors.webpage.bg = "{bg}"

c.colors.statusbar.normal.bg = "{bg}"
c.colors.statusbar.normal.fg = "{fg}"
c.colors.statusbar.insert.bg = "{accent}"
c.colors.statusbar.insert.fg = "{bg}"
c.colors.statusbar.command.bg = "{bg}"
c.colors.statusbar.command.fg = "{fg}"
c.colors.statusbar.url.fg = "{fg}"
c.colors.statusbar.url.success.http.fg = "{accent2}"
c.colors.statusbar.url.success.https.fg = "{accent2}"
c.colors.statusbar.url.error.fg = "{error}"
c.colors.statusbar.url.warn.fg = "{error}"
c.colors.statusbar.progress.bg = "{accent}"

c.colors.tabs.bar.bg = "{bg}"
c.colors.tabs.odd.bg = "{bg}"
c.colors.tabs.odd.fg = "{fg}"
c.colors.tabs.even.bg = "{bg}"
c.colors.tabs.even.fg = "{fg}"
c.colors.tabs.selected.odd.bg = "{selected_bg}"
c.colors.tabs.selected.odd.fg = "{selected_fg}"
c.colors.tabs.selected.even.bg = "{selected_bg}"
c.colors.tabs.selected.even.fg = "{selected_fg}"
c.colors.tabs.indicator.start = "{accent2}"
c.colors.tabs.indicator.stop = "{accent}"
c.colors.tabs.indicator.error = "{error}"
c.tabs.padding = {tabs_padding}

c.colors.completion.fg = "{fg}"
c.colors.completion.odd.bg = "{bg}"
c.colors.completion.even.bg = "{bg}"
c.colors.completion.category.bg = "{bg}"
c.colors.completion.category.fg = "{accent}"
c.colors.completion.category.border.top = "{muted}"
c.colors.completion.category.border.bottom = "{muted}"
c.colors.completion.item.selected.bg = "{selected_bg}"
c.colors.completion.item.selected.fg = "{selected_fg}"
c.colors.completion.item.selected.border.top = "{accent}"
c.colors.completion.item.selected.border.bottom = "{accent}"
c.colors.completion.item.selected.match.fg = "{selected_fg}"
c.colors.completion.match.fg = "{accent2}"
c.colors.completion.scrollbar.fg = "{accent}"
c.colors.completion.scrollbar.bg = "{bg}"

c.colors.hints.bg = "{accent}"
c.colors.hints.fg = "{bg}"
c.colors.hints.match.fg = "{accent2}"
c.hints.radius = {hints_radius}

c.colors.downloads.bar.bg = "{bg}"
c.colors.downloads.start.bg = "{accent}"
c.colors.downloads.start.fg = "{bg}"
c.colors.downloads.stop.bg = "{accent2}"
c.colors.downloads.stop.fg = "{bg}"
c.colors.downloads.error.bg = "{error}"
c.colors.downloads.error.fg = "{bg}"

c.colors.messages.info.bg = "{bg}"
c.colors.messages.info.fg = "{fg}"
c.colors.messages.info.border = "{muted}"
c.colors.messages.warning.bg = "{bg}"
c.colors.messages.warning.fg = "{error}"
c.colors.messages.warning.border = "{error}"
c.colors.messages.error.bg = "{error}"
c.colors.messages.error.fg = "{bg}"
c.colors.messages.error.border = "{error}"

c.colors.prompts.bg = "{bg}"
c.colors.prompts.fg = "{fg}"
c.colors.prompts.border = "1px solid {muted}"
c.colors.prompts.selected.bg = "{selected_bg}"
c.colors.prompts.selected.fg = "{selected_fg}"

c.colors.contextmenu.menu.bg = "{bg}"
c.colors.contextmenu.menu.fg = "{fg}"
c.colors.contextmenu.selected.bg = "{selected_bg}"
c.colors.contextmenu.selected.fg = "{selected_fg}"

# Start page wiring
_startpage = Path(__file__).parent / "startpage.html"
if _startpage.exists():
    _sp_url = f"file://{{_startpage}}"
    c.url.start_pages = [_sp_url]
    c.url.default_page = _sp_url
"""

    out_path = output_dir / "colors-wal.py"
    out_path.write_text(output, encoding="utf-8")

    # Wire into config.py if config.py exists and doesn't source it
    config_py = output_dir / "config.py"
    if config_py.exists():
        cfg_text = config_py.read_text(encoding="utf-8")
        if "colors-wal" not in cfg_text:
            separator = "\n" if cfg_text.endswith("\n") else "\n\n"
            cfg_text = cfg_text.rstrip() + separator + "\n# Load rice colors\ntry:\n    config.source('colors-wal.py')\nexcept Exception:\n    pass\n"
            config_py.write_text(cfg_text, encoding="utf-8")

    # Trigger live reload only if qutebrowser is already running
    try:
        res = subprocess.run(["pgrep", "-x", "qutebrowser"], capture_output=True, text=True)
        if res.returncode == 0:
            subprocess.run(
                ["qutebrowser", ":config-source"],
                timeout=2,
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
    except Exception:
        pass

    print(f"qutebrowser: {out_path} written and configuration updated")


if __name__ == "__main__":
    main()
