# Shared paths for the Quickshell Fish scripts.
set -g QS_YAHPAX_CACHE "$HOME/.cache/yahpax"
set -g QS_RUNTIME_DIR "$QS_YAHPAX_CACHE/runtime"
set -g QS_WAL_DIR "$QS_YAHPAX_CACHE/wal"
set -g QS_WAL_COLORS "$QS_WAL_DIR/colors.json"
set -g QS_RICE_CACHE "$QS_YAHPAX_CACHE/rice"
set -gx XDG_CACHE_HOME "$QS_YAHPAX_CACHE"
set -gx PYWAL_CACHE_DIR "$QS_WAL_DIR"
set -g QS_KITTY_CONFIG "$HOME/.config/kitty/kitty.conf"
set -g QS_FASTFETCH_CONFIG "$HOME/.config/fastfetch/yahpax"
set -g QS_WALLPAPER_THUMBNAILS "$QS_RICE_CACHE/wallpaper-thumbnails"
set -g QS_VIDEO_THUMBS "$QS_RICE_CACHE/wallpaper-thumbs"
set -g QS_CURRENT_WALLPAPER "$QS_RICE_CACHE/current-wallpaper"
set -g QS_CURRENT_PALETTE "$QS_RICE_CACHE/current-palette-image"
